services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    container_name: thumbs-mysql
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: thumbs
#      TZ: Asia/Shanghai
#    volumes:
#      - thumbs-mysql-data:/var/lib/mysql
#    command:
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    container_name: thumbs-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - thumbs-redis-data:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}


  rabbitmq:
    image: rabbitmq:4-management
    container_name: thumbs-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      TZ: Asia/Shanghai
    volumes:
      - thumbs-rabbitmq-data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:9.4.2
    restart: always
    container_name: thumbs-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - thumbs-es-data:/usr/share/elasticsearch/data

#
#  app:
#    build: .
#    container_name: thumbs-app
#    restart: always
#    depends_on:
#      - redis
#      - rabbitmq
#      - mysql
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#      TZ: Asia/Shanghai



volumes:
  thumbs-rabbitmq-data:
  thumbs-redis-data:
  thumbs-mysql-data:
  thumbs-es-data:
