spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://mysql:3306/thumbs

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}


  elasticsearch:
    uris: http://thumbs-elasticsearch:9200

  session:
    store-type: redis


springdoc:
  swagger-ui:
    enabled: true

app:
  upload:
    dir: /home/ubuntu/thumbs/upload
    url-prefix: /upload

