spring:
  application:
    name: Thumbs
  profiles:
    active: local


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名(deleted为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

server:
  servlet:
    session:
      timeout: 1h
    context-path: /api
  port: 8082


