spring:
  application:
    name: Thumbs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/thumbs

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

knife4j:
  setting:
    language: zh_cn
  basic:
    enable: true

springdoc:
  swagger-ui:
    enabled: true