spring:
  application:
    name: Thumbs
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    admin:
      service-url: http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/thumbs
  data:
    redis:
#      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      database: 0
      host: localhost
      port: 6379
      connect-timeout: 5000ms


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

knife4j:
  setting:
    language: zh_cn
  basic:
    enable: true

springdoc:
  swagger-ui:
    enabled: true
